---
AWSTemplateFormatVersion: "2010-09-09"

Description: This is creating a custom VPC with all vpc components

Resources:
  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - VPC1

  DHCP1:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: ec2.internal
      DomainNameServers:
        - AmazonProvidedDNS
      Tags:
        - DHCP1

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: VPC1
